[package]
name = "nilsadam_p2"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.1"
tokio = { version = "1.0", features = ["full"] }
tower-http = { version = "0.6.2", features = ["fs"] }

#[target.x86_64-unknown-linux-gnu]
#linker = "x86_64-linux-gnu-gcc"